<?php

define('INSTALL_SERVER_STEP', 'INSTALL_SERVER_STEP');
define('INSTALL_SERVER_STEP_ERROR', -1);
define('INSTALL_SERVER_STEP_INIT', 0);
define('INSTALL_SERVER_STEP_GENERATE_KEY', 1);
define('INSTALL_SERVER_STEP_COMPRESSING_SCRIPTS', 2);
define('INSTALL_SERVER_STEP_UPLOADING_SCRIPTS', 3);
define('INSTALL_SERVER_STEP_INSTALLING_SOFTWARES', 4);
define('INSTALL_SERVER_STEP_SECURING_SSH', 5);
define('INSTALL_SERVER_STEP_GETTING_SERVER_INFOS', 6);
define('INSTALL_SERVER_STEP_DONE', 7);
define('PATH_CACHE_FILE_INSTALL', PATH_ROOT_WEBSITE . '/cache/install');

define('DESINSTALL_SERVER_STEP', 'DESINSTALL_SERVER_STEP');
define('DESINSTALL_SERVER_STEP_ERROR', -1);
define('DESINSTALL_SERVER_STEP_INIT', 0);
define('DESINSTALL_SERVER_STEP_DESECURING_SSH', 1);
define('DESINSTALL_SERVER_STEP_DESINSTALLING_SOFTWARE', 2);
define('DESINSTALL_SERVER_STEP_DONE', 3);
define('PATH_CACHE_FILE_DESINSTALL', PATH_ROOT_WEBSITE . '/cache/desinstall');

define('UPDATE_SERVER_STEP', 'UPDATE_SERVER_STEP');
define('UPDATE_SERVER_STEP_ERROR', -1);
define('UPDATE_SERVER_STEP_INIT', 0);
define('UPDATE_SERVER_STEP_COMPRESSING_SCRIPTS', 1);
define('UPDATE_SERVER_STEP_UPLOADING_SCRIPTS', 2);
define('UPDATE_SERVER_STEP_UPDATING_SOFTWARE', 3);
define('UPDATE_SERVER_STEP_DONE', 4);
define('PATH_CACHE_FILE_UPDATE', PATH_ROOT_WEBSITE . '/cache/update');

define('INSTALL_VM_STEP', 'INSTALL_VM_STEP');
define('INSTALL_VM_STEP_ERROR', -1);
define('INSTALL_VM_STEP_INIT', 0);
define('INSTALL_VM_STEP_CONNECTION_SERVER', 1);
define('INSTALL_VM_STEP_INSTALLING', 2);
define('INSTALL_VM_STEP_SAVING_BDD', 3);
define('INSTALL_VM_STEP_DONE', 4);
define('PATH_CACHE_FILE_INSTALL_VM', PATH_ROOT_WEBSITE . '/cache/installVM');

define('DESINSTALL_VM_STEP', 'DESINSTALL_VM_STEP');
define('DESINSTALL_VM_STEP_ERROR', -1);
define('DESINSTALL_VM_STEP_INIT', 0);
define('DESINSTALL_VM_STEP_CONNECTION_SERVER', 1);
define('DESINSTALL_VM_STEP_DESINSTALLING', 2);
define('DESINSTALL_VM_STEP_DELETING_VM_BDD', 3);
define('DESINSTALL_VM_STEP_DONE', 4);
define('PATH_CACHE_FILE_DESINSTALL_VM', PATH_ROOT_WEBSITE . '/cache/desinstallVM');

define('UPDATE_VM_STEP', 'UPDATE_VM_STEP');
define('UPDATE_VM_STEP_ERROR', -1);
define('UPDATE_VM_STEP_INIT', 0);
define('UPDATE_VM_STEP_CONNECTION_VM', 1);
define('UPDATE_VM_STEP_UPDATING_SOFTWARE', 2);
define('UPDATE_VM_STEP_DONE', 3);
define('PATH_CACHE_FILE_UPDATE_VM', PATH_ROOT_WEBSITE . '/cache/updateVM');

define('LAUNCH_ALGO_STEP', 'LAUNCH_ALGO_STEP');
define('LAUNCH_ALGO_STEP_ERROR', -1);
define('LAUNCH_ALGO_STEP_COMPRESSING_SCRIPTS', 1);
define('LAUNCH_ALGO_STEP_UPLOADING_SCRIPTS', 2);
define('LAUNCH_ALGO_STEP_DONE', 3);
define('PATH_CACHE_FILE_LAUNCH_ALGO', PATH_ROOT_WEBSITE . '/cache/launchAlgo');

define('REGEX_PROMPT', '/.*@.*[$|#]/');
define('PATH_MASTER_SCRIPT_SERVER_SLAVE', "ScriptServerSlave");
define('PATH_MASTER_SCRIPT_SERVER_SLAVE_TO_UPLOAD', PATH_MASTER_SCRIPT_SERVER_SLAVE . "/ScriptServerSFTP");
define('PATH_MASTER_SCRIPT_SERVER_SLAVE_TO_UPLOAD_ARCHIVE', PATH_MASTER_SCRIPT_SERVER_SLAVE_TO_UPLOAD . "/ScriptServerSFTP.tar");
define('PATH_MASTER_PRIVATE_KEY_SSH', "SSHKeys/id_server_");
define('PATH_MASTER_PUBLIC_KEY_SSH', PATH_MASTER_SCRIPT_SERVER_SLAVE . "/ScriptServerSFTP/authorized_keys");
define('PATH_DIR_CONFIG_SSH', "/etc/ssh");
define('PATH_FILE_CONFIG_SSH', PATH_DIR_CONFIG_SSH . "/sshd_config");
define('PATH_FILE_CONFIG_SSH_SAVE', PATH_FILE_CONFIG_SSH . ".save");
define('PATH_DIR_KEY_SSH', "~/.ssh");
define('PATH_FILE_PUBLIC_KEY_SSH', PATH_DIR_KEY_SSH . "/authorized_keys");
define('PATH_FILE_AUTHORIZED_KEYS', '%h/.ssh/authorized_keys');
define('SSH_PORT', "22");
define('SSH_PROTOCOL', "2");
define('LOGIN_GRACE_TIME', "20");
define('MAX_AUTH_TRIES', "1");
define('MAX_STARTUPS', "2");
define('GROUP_SSH_ALLOW', "sshusers");

define('MSG_DELIMITER', '#/$/#:');

define('PATH_MASTER_SCRIPT_ALGO', "ScriptAlgoVM");
define('PATH_MASTER_SCRIPT_ALGO_TO_UPLOAD', PATH_MASTER_SCRIPT_ALGO . "/ScriptAlgoFTP");
define('PATH_MASTER_SCRIPT_ALGO_TO_UPLOAD_ARCHIVE', PATH_MASTER_SCRIPT_ALGO_TO_UPLOAD . "/ScriptAlgoFTP.tar");

?>