<?php

define('INSTALL_SERVER_STEP', 'INSTALL_SERVER_STEP');
define('INSTALL_SERVER_STEP_ERROR', -1);
define('INSTALL_SERVER_STEP_INIT', 0);
define('INSTALL_SERVER_STEP_GENERATE_KEY', 1);
define('INSTALL_SERVER_STEP_COMPRESSING_SCRIPTS', 2);
define('INSTALL_SERVER_STEP_UPLOADING_SCRIPTS', 3);
define('INSTALL_SERVER_STEP_INSTALLING_SOFTWARES', 4);
define('INSTALL_SERVER_STEP_SECURING_SSH', 5);
define('INSTALL_SERVER_STEP_GETTING_SERVER_INFOS', 6);
define('INSTALL_SERVER_STEP_DONE', 7);

define('DESINSTALL_SERVER_STEP', 'DESINSTALL_SERVER_STEP');
define('DESINSTALL_SERVER_STEP_ERROR', -1);
define('DESINSTALL_SERVER_STEP_INIT', 0);
define('DESINSTALL_SERVER_STEP_DESECURING_SSH', 1);
define('DESINSTALL_SERVER_STEP_DESINSTALLING_SOFTWARE', 2);
define('DESINSTALL_SERVER_STEP_DONE', 3);


define('INSTALL_VM_STEP', 'INSTALL_VM_STEP');
define('INSTALL_VM_STEP_ERROR', -1);
define('INSTALL_VM_STEP_INIT', 0);
define('INSTALL_VM_STEP_CONNECTION_SERVER', 1);
define('INSTALL_VM_STEP_INSTALLING', 2);
define('INSTALL_VM_STEP_SAVING_BDD', 3);
define('INSTALL_VM_STEP_DONE', 4);

define('DESINSTALL_VM_STEP', 'DESINSTALL_VM_STEP');
define('DESINSTALL_VM_STEP_ERROR', -1);
define('DESINSTALL_VM_STEP_INIT', 0);
define('DESINSTALL_VM_STEP_CONNECTION_SERVER', 1);
define('DESINSTALL_VM_STEP_DESINSTALLING', 2);
define('DESINSTALL_VM_STEP_DELETING_VM_BDD', 3);
define('DESINSTALL_VM_STEP_DONE', 4);

define('PATH_MASTER_SCRIPT_SERVER_SLAVE', "ScriptServerSlave");
define('PATH_MASTER_SCRIPT_SERVER_SLAVE_TO_UPLOAD', PATH_MASTER_SCRIPT_SERVER_SLAVE . "/ScriptServerSFTP");
define('PATH_MASTER_SCRIPT_SERVER_SLAVE_TO_UPLOAD_ARCHIVE', PATH_MASTER_SCRIPT_SERVER_SLAVE_TO_UPLOAD . "/ScriptServerSFTP.tar");
define('PATH_MASTER_PRIVATE_KEY_SSH', "SSHKeys/id_server_");
define('PATH_MASTER_PUBLIC_KEY_SSH', PATH_MASTER_SCRIPT_SERVER_SLAVE . "/ScriptServerSFTP/authorized_keys");
define('PATH_DIR_CONFIG_SSH', "/etc/ssh");
define('PATH_FILE_CONFIG_SSH', PATH_DIR_CONFIG_SSH . "/sshd_config");
define('PATH_FILE_CONFIG_SSH_SAVE', PATH_FILE_CONFIG_SSH . ".save");
define('PATH_DIR_KEY_SSH', "~/.ssh");
define('PATH_FILE_PUBLIC_KEY_SSH', PATH_DIR_KEY_SSH . "/authorized_keys");
define('PATH_FILE_AUTHORIZED_KEYS', '%h/.ssh/authorized_keys');
define('SSH_PORT', "22");
define('SSH_PROTOCOL', "2");
define('LOGIN_GRACE_TIME', "20");
define('MAX_AUTH_TRIES', "1");
define('MAX_STARTUPS', "2");
define('GROUP_SSH_ALLOW', "sshusers");

define('MSG_DELIMITER', '#/$/#:');

?>