<?php

define('INSTALL_SERVER_STEP', 'INSTALL_SERVER_STEP');
define('INSTALL_SERVER_STEP_ERROR', -1);
define('INSTALL_SERVER_STEP_INIT', 0);
define('INSTALL_SERVER_STEP_DONE', 1);

$PATH_MASTER_PUBLIC_KEY_SSH= "../SSHKeys/id_server";
$PATH_DIR_CONFIG_SSH= "/etc/ssh";
$PATH_FILE_CONFIG_SSH= $PATH_DIR_CONFIG_SSH . "/sshd_config";
$PATH_FILE_CONFIG_SSH_SAVE= $PATH_FILE_CONFIG_SSH . ".save";
$PATH_DIR_KEY_SSH="~/.ssh";
$PATH_FILE_PRIVATE_KEY_SSH= $PATH_DIR_KEY_SSH . "/id_server";
$PATH_FILE_PUBLIC_KEY_SSH= $PATH_FILE_PRIVATE_KEY_SSH . ".pub";
$SSH_PORT="9876";
$SSH_PROTOCOL="33333";
$LOGIN_GRACE_TIME="20";
$MAX_AUTH_TRIES="1";
$MAX_STARTUPS="2";
$GROUP_SSH_ALLOW="sshusers";

?>